### ISSUE TITLE
Can't install GradeMe

### ISSUE THREAD

**Issue by Middle-555** [JCluzet/GrademeBash#38]
Hello, when i try to install GradeMe on my computer the compilation doesn't work. I tried to fix it but everything i had done didnt work.

"- Your OS: Darwin MacBook-Pro-de-Middle.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:33:00 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6031 arm64
      - The error message:
ld: warning: search path '/usr/local/lib' is not a directory"

<img width="563" alt="Capture d’écran 2023-12-12 à 18 25 27" src="https://github.com/JCluzet/GrademeBash/assets/118801041/d1b364d4-5039-423b-864b-2db9f3644bb5">

**Comment by Middle-555** [comment]
Fixed. The problem was the accessibility of lib.

**Comment by JCluzet** [comment]
Hello @Middle-555 👋

Thank you for the update and for resolving the issue with the library accessibility. Could you please provide me with some details on the fix you implemented? This would help us document the issue and the solution for future reference and to assist other users who might encounter the same problem.

Best regards,
JCluzet

**Comment by Middle-555** [comment]
My problem was that `/usr/local/include` or `ls /usr/local/lib` wasn't accessible.  I don't know why but everytime that i tried to use `cd /usr/local/lib` to enter it an error message appeared `/usr/local/lib_backup: Not a directory` but when i used `file /usr/local/lib` `User MacBook-Pro-de-Middle:~ root# file /usr/local/lib /usr/local/lib: directory` i had the confirmation that i was a directory. 
After a long exchange with ChatGPT i came to the conclusion that i had to recreate a new lib directory.

`sudo mv /usr/local/lib  /tmp/lib_backup`
`sudo mkdir /usr/local/lib`
`sudo mv /tmp/lib_backup /usr/local`

I hope it will help u and if u need more precision feel free to ask ! 
Ps: thank you for GradeMe, which is helping me prepare for my ExamRank2.
